/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const scanline_flood_fill: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => number;
export const scanline_flood_fill_with_mask: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number) => number;
export const __wbg_patchbufferrgbaoption_free: (a: number, b: number) => void;
export const __wbg_get_patchbufferrgbaoption_antialias_mode: (a: number) => number;
export const __wbg_set_patchbufferrgbaoption_antialias_mode: (a: number, b: number) => void;
export const __wbg_get_patchbufferrgbaoption_flip_x: (a: number) => number;
export const __wbg_set_patchbufferrgbaoption_flip_x: (a: number, b: number) => void;
export const __wbg_get_patchbufferrgbaoption_flip_y: (a: number) => number;
export const __wbg_set_patchbufferrgbaoption_flip_y: (a: number, b: number) => void;
export const patchbufferrgbaoption_new: (a: number, b: number, c: number) => number;
export const patch_buffer_rgba: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number];
export const patch_buffer_rgba_instant: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => void;
export const raw_to_webp: (a: number, b: number, c: number, d: number) => [number, number];
export const webp_to_raw: (a: number, b: number, c: number, d: number) => [number, number];
export const raw_to_png: (a: number, b: number, c: number, d: number) => [number, number];
export const png_to_raw: (a: number, b: number, c: number, d: number) => [number, number];
export const resize: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number];
export const __wbg_rgbabuffer_free: (a: number, b: number) => void;
export const rgbabuffer_new: (a: number, b: number) => number;
export const rgbabuffer_width: (a: number) => number;
export const rgbabuffer_height: (a: number) => number;
export const rgbabuffer_len: (a: number) => number;
export const rgbabuffer_is_empty: (a: number) => number;
export const rgbabuffer_ptr: (a: number) => number;
export const rgbabuffer_data: (a: number) => any;
export const rgbabuffer_exportWebp: (a: number) => [number, number];
export const rgbabuffer_exportPng: (a: number) => [number, number];
export const rgbabuffer_importRaw: (a: number, b: number, c: number, d: number, e: number) => number;
export const rgbabuffer_importWebp: (a: number, b: number, c: number, d: number, e: number) => number;
export const rgbabuffer_importPng: (a: number, b: number, c: number, d: number, e: number) => number;
export const rgbabuffer_resize_instant: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const rgbabuffer_floodFill: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const rgbabuffer_floodFillWithMask: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => number;
export const rgbabuffer_blitFromRaw: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => void;
export const rgbabuffer_blitFromBuffer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const rgbabuffer_sliceWithMask: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const rgbabuffer_cropWithMask: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
